# taka jest najczesciej przyjmowana praktyka
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/book-service/**
          - id: payment-validation-service
            uri: lb://payment-validation-service
            predicates:
              - Path=/payment-validation-service/**
          - id: ebook-delivery-service
            uri: lb://ebook-delivery-service
            predicates:
              - Path=/ebook-delivery-service/**